title: Shuangjie Fan's Homepage
page-top-title: Shuangjie Fan
top-section-bg-text: Artificial Intelligence
home-subtitle: Shuangjie Fan&ensp;|&ensp;樊双杰
copyright-text: '&copy; Shuangjie Fan 2024-2025. All Rights Reserved.'
